-- ============================================================
--  03_SilverDB_Setup.sql
--  Analytics-ready star schema.
--
--  SURROGATE KEY DESIGN:
--    Every Silver table has an IDENTITY surrogate key (e.g. CustomerKey).
--    The natural key in the warehouse is SourceSystem + SourceNativeID.
--    Example: CustomerID=1001 from RetailMart -> CustomerKey = new INT
--             CustomerID=2001 from LogiShip   -> CustomerKey = new INT
--    This guarantees uniqueness across both sources with no collision.
--
--  SCD TYPE 2 on dim_customer and dim_product:
--    IsCurrent, ValidFrom, ValidTo columns track history.
--
--  dim_date is generated (spine 2018-01-01 to 2030-12-31).
-- ============================================================

USE master;
GO
IF EXISTS (SELECT 1 FROM sys.databases WHERE name = 'SilverDB')
BEGIN
    ALTER DATABASE SilverDB SET SINGLE_USER WITH ROLLBACK IMMEDIATE;
    DROP DATABASE SilverDB;
END
GO
CREATE DATABASE SilverDB COLLATE SQL_Latin1_General_CP1_CI_AS;
GO
USE SilverDB;
GO

-- ============================================================
-- CONTROL TABLE
-- ============================================================
CREATE TABLE dbo.SilverLoadLog (
    BatchID        INT          IDENTITY(1,1) PRIMARY KEY,
    BronzeBatchID  INT          NOT NULL,
    RunStartedAt   DATETIME     NOT NULL DEFAULT GETDATE(),
    RunFinishedAt  DATETIME     NULL,
    Status         VARCHAR(20)  NOT NULL DEFAULT 'Running',
    Notes          VARCHAR(500) NULL
);
GO

-- ============================================================
-- dim_date  (static calendar spine — generated by SP)
-- ============================================================
CREATE TABLE dbo.dim_date (
    DateKey        INT          NOT NULL PRIMARY KEY,   -- YYYYMMDD integer
    FullDate       DATE         NOT NULL UNIQUE,
    DayOfWeek      TINYINT      NOT NULL,               -- 1=Sun..7=Sat
    DayName        VARCHAR(10)  NOT NULL,
    DayOfMonth     TINYINT      NOT NULL,
    DayOfYear      SMALLINT     NOT NULL,
    WeekOfYear     TINYINT      NOT NULL,
    MonthNumber    TINYINT      NOT NULL,
    MonthName      VARCHAR(10)  NOT NULL,
    Quarter        TINYINT      NOT NULL,
    Year           SMALLINT     NOT NULL,
    IsWeekend      BIT          NOT NULL,
    IsHoliday      BIT          NOT NULL DEFAULT 0,
    FiscalYear     SMALLINT     NOT NULL,               -- Apr-Mar Indian FY
    FiscalQuarter  TINYINT      NOT NULL
);
GO

-- ============================================================
-- dim_customer  (SCD Type 2)
-- Natural key: SourceSystem + SourceCustomerID
-- ============================================================
CREATE TABLE dbo.dim_customer (
    CustomerKey       INT           IDENTITY(1,1) PRIMARY KEY,
    SourceSystem      VARCHAR(30)   NOT NULL,
    SourceCustomerID  INT           NOT NULL,
    FirstName         VARCHAR(100)  NULL,
    LastName          VARCHAR(100)  NULL,
    FullName          VARCHAR(205)  NULL,               -- derived: FirstName + ' ' + LastName
    Email             VARCHAR(255)  NULL,
    Phone             VARCHAR(20)   NULL,
    DateOfBirth       DATE          NULL,
    AgeYears          INT           NULL,               -- derived at load time
    Gender            VARCHAR(10)   NULL,               -- standardised: Male/Female/Other/Unknown
    LoyaltyTier       VARCHAR(20)   NULL,               -- standardised: Bronze/Silver/Gold/Platinum/Unknown
    RegisteredDate    DATETIME      NULL,
    IsActive          BIT           NULL,
    CountryCode       CHAR(2)       NULL,
    -- SCD2
    IsCurrent         BIT           NOT NULL DEFAULT 1,
    ValidFrom         DATETIME      NOT NULL DEFAULT GETDATE(),
    ValidTo           DATETIME      NULL,               -- NULL = current record
    -- audit
    Slv_LoadedAt      DATETIME      NOT NULL DEFAULT GETDATE(),
    Slv_BatchID       INT           NOT NULL,
    CONSTRAINT UQ_DimCustomer_Current UNIQUE (SourceSystem, SourceCustomerID, IsCurrent)
);
GO
CREATE INDEX IX_DimCustomer_NatKey ON dbo.dim_customer (SourceSystem, SourceCustomerID, IsCurrent);
GO

-- ============================================================
-- dim_product  (SCD Type 2)
-- Natural key: SourceSystem + SourceProductID
-- ============================================================
CREATE TABLE dbo.dim_product (
    ProductKey        INT            IDENTITY(1,1) PRIMARY KEY,
    SourceSystem      VARCHAR(30)    NOT NULL,
    SourceProductID   INT            NOT NULL,
    SKU_Barcode       VARCHAR(50)    NULL,
    ProductName       VARCHAR(255)   NULL,
    CategoryKey       INT            NULL,              -- FK -> dim_category
    BasePrice         DECIMAL(10,2)  NULL,
    CostPrice         DECIMAL(10,2)  NULL,
    GrossMarginPct    DECIMAL(6,2)   NULL,              -- derived: (BasePrice-CostPrice)/BasePrice*100
    StockQty          INT            NULL,
    Weight_kg         DECIMAL(10,4)  NULL,
    IsActive          BIT            NULL,
    LaunchDate        DATE           NULL,
    -- SCD2
    IsCurrent         BIT            NOT NULL DEFAULT 1,
    ValidFrom         DATETIME       NOT NULL DEFAULT GETDATE(),
    ValidTo           DATETIME       NULL,
    -- audit
    Slv_LoadedAt      DATETIME       NOT NULL DEFAULT GETDATE(),
    Slv_BatchID       INT            NOT NULL,
    CONSTRAINT UQ_DimProduct_Current UNIQUE (SourceSystem, SourceProductID, IsCurrent)
);
GO
CREATE INDEX IX_DimProduct_NatKey ON dbo.dim_product (SourceSystem, SourceProductID, IsCurrent);
GO

-- ============================================================
-- dim_category  (SCD Type 1 — simple overwrite)
-- Natural key: SourceSystem + SourceCategoryID
-- ============================================================
CREATE TABLE dbo.dim_category (
    CategoryKey       INT           IDENTITY(1,1) PRIMARY KEY,
    SourceSystem      VARCHAR(30)   NOT NULL,
    SourceCategoryID  INT           NOT NULL,
    CategoryName      VARCHAR(100)  NULL,
    ParentCategoryKey INT           NULL,               -- self-ref to CategoryKey
    IsActive          BIT           NULL,
    Slv_LoadedAt      DATETIME      NOT NULL DEFAULT GETDATE(),
    Slv_BatchID       INT           NOT NULL,
    CONSTRAINT UQ_DimCategory UNIQUE (SourceSystem, SourceCategoryID)
);
GO

-- ============================================================
-- dim_promotion
-- Natural key: SourceSystem + SourcePromoID
-- ============================================================
CREATE TABLE dbo.dim_promotion (
    PromoKey         INT            IDENTITY(1,1) PRIMARY KEY,
    SourceSystem     VARCHAR(30)    NOT NULL,
    SourcePromoID    INT            NOT NULL,
    PromoCode        VARCHAR(50)    NULL,
    Description      VARCHAR(255)   NULL,
    DiscountType     VARCHAR(20)    NULL,
    DiscountValue    DECIMAL(10,2)  NULL,
    MinOrderValue    DECIMAL(10,2)  NULL,
    StartDate        DATE           NULL,
    EndDate          DATE           NULL,
    IsActive         BIT            NULL,
    IsExpired        BIT            NULL,
    Slv_LoadedAt     DATETIME       NOT NULL DEFAULT GETDATE(),
    Slv_BatchID      INT            NOT NULL,
    CONSTRAINT UQ_DimPromo UNIQUE (SourceSystem, SourcePromoID)
);
GO

-- ============================================================
-- dim_location  (derived from order city/state/pincode)
-- Natural key: City + State + PinCode (normalised)
-- ============================================================
CREATE TABLE dbo.dim_location (
    LocationKey  INT           IDENTITY(1,1) PRIMARY KEY,
    City         VARCHAR(100)  NULL,
    State        VARCHAR(100)  NULL,
    PinCode      VARCHAR(10)   NULL,
    CountryCode  CHAR(2)       NOT NULL DEFAULT 'IN',
    Slv_LoadedAt DATETIME      NOT NULL DEFAULT GETDATE(),
    Slv_BatchID  INT           NOT NULL,
    CONSTRAINT UQ_DimLocation UNIQUE (City, State, PinCode)
);
GO

-- ============================================================
-- dim_payment_method
-- Derived from distinct PaymentMethod values across both sources
-- ============================================================
CREATE TABLE dbo.dim_payment_method (
    PaymentMethodKey  INT           IDENTITY(1,1) PRIMARY KEY,
    PaymentMethod     VARCHAR(50)   NOT NULL UNIQUE,
    PaymentCategory   VARCHAR(30)   NULL    -- Digital / Cash / Finance
);
GO
INSERT INTO dbo.dim_payment_method (PaymentMethod, PaymentCategory) VALUES
('UPI',          'Digital'),
('Credit Card',  'Digital'),
('Debit Card',   'Digital'),
('Net Banking',  'Digital'),
('COD',          'Cash'),
('Wallet',       'Digital'),
('Card',         'Digital'),
('NetBanking',   'Digital'),
('EMI',          'Finance'),
('Unknown',      NULL);
GO

-- ============================================================
-- dim_warehouse  (LogiShip only)
-- Natural key: SourceWarehouseID (single source)
-- ============================================================
CREATE TABLE dbo.dim_warehouse (
    WarehouseKey      INT           IDENTITY(1,1) PRIMARY KEY,
    SourceWarehouseID INT           NOT NULL UNIQUE,
    WarehouseName     VARCHAR(150)  NULL,
    City              VARCHAR(100)  NULL,
    State             VARCHAR(100)  NULL,
    CountryCode       CHAR(2)       NULL,
    CapacityUnits     INT           NULL,
    IsOperational     BIT           NULL,
    ManagerName       VARCHAR(100)  NULL,
    OpenedOn          DATE          NULL,
    Slv_LoadedAt      DATETIME      NOT NULL DEFAULT GETDATE(),
    Slv_BatchID       INT           NOT NULL
);
GO

-- ============================================================
-- dim_supplier  (LogiShip only)
-- Natural key: SourceSupplierID
-- ============================================================
CREATE TABLE dbo.dim_supplier (
    SupplierKey       INT            IDENTITY(1,1) PRIMARY KEY,
    SourceSupplierID  INT            NOT NULL UNIQUE,
    SupplierName      VARCHAR(200)   NULL,
    Email             VARCHAR(255)   NULL,
    Phone             VARCHAR(20)    NULL,
    CountryCode       CHAR(2)        NULL,
    LeadDays          INT            NULL,
    PayTerms          VARCHAR(50)    NULL,
    Rating            DECIMAL(3,1)   NULL,
    IsActive          BIT            NULL,
    OnboardDate       DATE           NULL,
    Slv_LoadedAt      DATETIME       NOT NULL DEFAULT GETDATE(),
    Slv_BatchID       INT            NOT NULL
);
GO

-- ============================================================
-- fact_sales
-- Grain: one row per order line item
-- Degenerate dimensions: SourceOrderID, SourceLineItemID
-- ============================================================
CREATE TABLE dbo.fact_sales (
    SalesKey          INT            IDENTITY(1,1) PRIMARY KEY,
    -- dimensions
    OrderDateKey      INT            NULL,   -- FK dim_date
    CustomerKey       INT            NULL,   -- FK dim_customer
    ProductKey        INT            NULL,   -- FK dim_product
    CategoryKey       INT            NULL,   -- FK dim_category
    LocationKey       INT            NULL,   -- FK dim_location
    PromoKey          INT            NULL,   -- FK dim_promotion (nullable)
    PaymentMethodKey  INT            NULL,   -- FK dim_payment_method
    -- degenerate
    SourceSystem      VARCHAR(30)    NOT NULL,
    SourceOrderID     INT            NULL,
    SourceLineItemID  INT            NULL,
    OrderStatus       VARCHAR(30)    NULL,
    -- measures
    Quantity          INT            NULL,
    UnitPrice         DECIMAL(10,2)  NULL,
    LineTotal         DECIMAL(10,2)  NULL,
    Discount          DECIMAL(10,2)  NULL,
    GrossAmount       DECIMAL(10,2)  NULL,   -- from order header
    TaxAmount         DECIMAL(10,2)  NULL,
    ShippingAmount    DECIMAL(10,2)  NULL,
    NetPayable        DECIMAL(10,2)  NULL,
    AmountPaid        DECIMAL(10,2)  NULL,   -- from payments
    LineDiscrepancy   BIT            NULL,   -- from bronze flag
    IsFulfilled       BIT            NULL,
    -- audit
    Slv_LoadedAt      DATETIME       NOT NULL DEFAULT GETDATE(),
    Slv_BatchID       INT            NOT NULL
);
GO
CREATE INDEX IX_FactSales_DateKey     ON dbo.fact_sales (OrderDateKey);
CREATE INDEX IX_FactSales_CustomerKey ON dbo.fact_sales (CustomerKey);
CREATE INDEX IX_FactSales_ProductKey  ON dbo.fact_sales (ProductKey);
GO

-- ============================================================
-- fact_returns
-- Grain: one row per return event
-- ============================================================
CREATE TABLE dbo.fact_returns (
    ReturnKey         INT            IDENTITY(1,1) PRIMARY KEY,
    ReturnDateKey     INT            NULL,   -- FK dim_date
    CustomerKey       INT            NULL,   -- FK dim_customer (via order)
    ProductKey        INT            NULL,   -- FK dim_product (via SKU/BarCode lookup)
    WarehouseKey      INT            NULL,   -- FK dim_warehouse
    -- degenerate
    SourceSystem      VARCHAR(30)    NOT NULL,
    SourceReturnID    INT            NULL,
    SourceOrderID     INT            NULL,
    SourceShipmentID  INT            NULL,
    -- measures
    ReturnQty         INT            NULL,
    RefundAmount      DECIMAL(10,2)  NULL,
    ReturnReason      VARCHAR(100)   NULL,
    ReturnStatus      VARCHAR(30)    NULL,
    IsRefunded        BIT            NULL,
    -- audit
    Slv_LoadedAt      DATETIME       NOT NULL DEFAULT GETDATE(),
    Slv_BatchID       INT            NOT NULL
);
GO
CREATE INDEX IX_FactReturns_DateKey ON dbo.fact_returns (ReturnDateKey);
GO

-- ============================================================
-- fact_inventory_snapshot
-- Grain: one row per BarCode x Warehouse x Load date
-- ============================================================
CREATE TABLE dbo.fact_inventory_snapshot (
    InventorySnapshotKey  INT            IDENTITY(1,1) PRIMARY KEY,
    SnapshotDateKey       INT            NULL,   -- FK dim_date
    ProductKey            INT            NULL,   -- FK dim_product (via BarCode)
    WarehouseKey          INT            NULL,   -- FK dim_warehouse
    SupplierKey           INT            NULL,   -- FK dim_supplier
    -- degenerate
    SourceSystem          VARCHAR(30)    NOT NULL,
    BarCode               VARCHAR(50)    NULL,
    -- measures
    QtyOnHand             INT            NULL,
    QtyReserved           INT            NULL,
    QtyAvailable          INT            NULL,
    ReorderLevel          INT            NULL,
    ReplenishQty          INT            NULL,
    IsLowStock            BIT            NULL,   -- derived: QtyAvailable <= ReorderLevel
    -- audit
    Slv_LoadedAt          DATETIME       NOT NULL DEFAULT GETDATE(),
    Slv_BatchID           INT            NOT NULL
);
GO

-- ============================================================
-- fact_shipments
-- Grain: one row per shipment
-- ============================================================
CREATE TABLE dbo.fact_shipments (
    ShipmentFactKey    INT            IDENTITY(1,1) PRIMARY KEY,
    ShipmentDateKey    INT            NULL,   -- FK dim_date (dispatch date)
    DeliveryDateKey    INT            NULL,   -- FK dim_date (actual delivery)
    CustomerKey        INT            NULL,   -- FK dim_customer (via order)
    WarehouseKey       INT            NULL,   -- FK dim_warehouse
    -- degenerate
    SourceSystem       VARCHAR(30)    NOT NULL,
    SourceShipmentID   INT            NULL,
    SourceOrderID      INT            NULL,
    CarrierCode        VARCHAR(20)    NULL,
    TrackingNumber     VARCHAR(100)   NULL,
    ShipmentStatus     VARCHAR(30)    NULL,
    -- measures
    ShippingCost       DECIMAL(10,2)  NULL,
    ChargedWeightKg    DECIMAL(8,3)   NULL,
    DeliveryDays       INT            NULL,
    IsLateDelivery     BIT            NULL,
    -- audit
    Slv_LoadedAt       DATETIME       NOT NULL DEFAULT GETDATE(),
    Slv_BatchID        INT            NOT NULL
);
GO

-- ============================================================
-- fact_procurement
-- Grain: one row per purchase order
-- ============================================================
CREATE TABLE dbo.fact_procurement (
    ProcurementKey    INT            IDENTITY(1,1) PRIMARY KEY,
    PODateKey         INT            NULL,   -- FK dim_date
    ArrivalDateKey    INT            NULL,   -- FK dim_date (actual arrival)
    SupplierKey       INT            NULL,   -- FK dim_supplier
    WarehouseKey      INT            NULL,   -- FK dim_warehouse
    -- degenerate
    SourceSystem      VARCHAR(30)    NOT NULL,
    SourcePOID        INT            NULL,
    POStatus          VARCHAR(30)    NULL,
    Currency          CHAR(3)        NULL,
    -- measures
    TotalValue        DECIMAL(12,2)  NULL,
    LeadTimeDays      INT            NULL,
    IsDelayed         BIT            NULL,
    -- audit
    Slv_LoadedAt      DATETIME       NOT NULL DEFAULT GETDATE(),
    Slv_BatchID       INT            NOT NULL
);
GO

PRINT 'SilverDB created — 8 dimensions + 5 fact tables ready.';
GO
