-- ============================================================
--  06_SP_Bronze_To_Silver.sql
--  Stored procedures: BronzeDB → SilverDB
--
--  KEY DESIGN:
--    Surrogate keys are generated by IDENTITY columns.
--    Natural key = SourceSystem + SourceNativeID (always preserved).
--    SCD2 on dim_customer and dim_product:
--      - If attribute changes: expire old row (ValidTo=now, IsCurrent=0)
--        and INSERT new row with IsCurrent=1.
--    Dimensions loaded before facts (referential integrity in Silver).
--    dim_date seeded once by usp_Slv_Seed_DateDim.
-- ============================================================

USE SilverDB;
GO

-- ============================================================
-- SP: usp_Slv_Seed_DateDim  (run once; idempotent)
-- ============================================================
CREATE OR ALTER PROCEDURE dbo.usp_Slv_Seed_DateDim
    @StartDate DATE = '2018-01-01',
    @EndDate   DATE = '2030-12-31'
AS
BEGIN
    SET NOCOUNT ON;

    DECLARE @d DATE = @StartDate;
    WHILE @d <= @EndDate
    BEGIN
        IF NOT EXISTS (SELECT 1 FROM dbo.dim_date WHERE FullDate = @d)
        BEGIN
            INSERT INTO dbo.dim_date
                (DateKey, FullDate, DayOfWeek, DayName, DayOfMonth, DayOfYear,
                 WeekOfYear, MonthNumber, MonthName, Quarter, Year,
                 IsWeekend, IsHoliday, FiscalYear, FiscalQuarter)
            VALUES (
                CAST(FORMAT(@d,'yyyyMMdd') AS INT),
                @d,
                DATEPART(WEEKDAY, @d),
                DATENAME(WEEKDAY, @d),
                DAY(@d),
                DATEPART(DAYOFYEAR, @d),
                DATEPART(WEEK, @d),
                MONTH(@d),
                DATENAME(MONTH, @d),
                DATEPART(QUARTER, @d),
                YEAR(@d),
                CASE WHEN DATEPART(WEEKDAY,@d) IN (1,7) THEN 1 ELSE 0 END,
                0,
                -- Indian FY: Apr-Mar
                CASE WHEN MONTH(@d) >= 4 THEN YEAR(@d) ELSE YEAR(@d)-1 END,
                CASE
                    WHEN MONTH(@d) IN (4,5,6)   THEN 1
                    WHEN MONTH(@d) IN (7,8,9)   THEN 2
                    WHEN MONTH(@d) IN (10,11,12) THEN 3
                    ELSE 4
                END
            );
        END;
        SET @d = DATEADD(DAY, 1, @d);
    END;
    PRINT CONCAT('dim_date seeded: ', @StartDate, ' → ', @EndDate);
END;
GO

-- ============================================================
-- SP: usp_Slv_Load_DimCategory
-- ============================================================
CREATE OR ALTER PROCEDURE dbo.usp_Slv_Load_DimCategory
    @BrzBatchID INT,
    @SlvBatchID INT
AS
BEGIN
    SET NOCOUNT ON;

    -- SCD1: simple upsert
    MERGE dbo.dim_category AS tgt
    USING (
        SELECT SourceSystem, SourceCategoryID, CategoryName, IsActive
        FROM BronzeDB.dbo.br_categories
        WHERE Brz_BatchID = @BrzBatchID
    ) AS src
    ON tgt.SourceSystem = src.SourceSystem
       AND tgt.SourceCategoryID = src.SourceCategoryID

    WHEN MATCHED THEN UPDATE SET
        tgt.CategoryName = src.CategoryName,
        tgt.IsActive     = src.IsActive,
        tgt.Slv_LoadedAt = GETDATE(),
        tgt.Slv_BatchID  = @SlvBatchID

    WHEN NOT MATCHED THEN INSERT
        (SourceSystem, SourceCategoryID, CategoryName, IsActive,
         Slv_LoadedAt, Slv_BatchID)
    VALUES
        (src.SourceSystem, src.SourceCategoryID, src.CategoryName, src.IsActive,
         GETDATE(), @SlvBatchID);

    -- Self-referencing ParentCategoryKey update (second pass after all rows inserted)
    UPDATE tgt
    SET tgt.ParentCategoryKey = parent.CategoryKey
    FROM dbo.dim_category tgt
    JOIN BronzeDB.dbo.br_categories brz
        ON brz.SourceSystem = tgt.SourceSystem
        AND brz.SourceCategoryID = tgt.SourceCategoryID
        AND brz.Brz_BatchID = @BrzBatchID
    JOIN dbo.dim_category parent
        ON parent.SourceSystem = tgt.SourceSystem
        AND parent.SourceCategoryID = brz.ParentCategoryID
    WHERE brz.ParentCategoryID IS NOT NULL;
END;
GO

-- ============================================================
-- SP: usp_Slv_Load_DimProduct  (SCD2)
-- ============================================================
CREATE OR ALTER PROCEDURE dbo.usp_Slv_Load_DimProduct
    @BrzBatchID INT,
    @SlvBatchID INT
AS
BEGIN
    SET NOCOUNT ON;

    -- Step 1: Expire changed rows
    UPDATE tgt
    SET tgt.IsCurrent = 0,
        tgt.ValidTo   = GETDATE()
    FROM dbo.dim_product tgt
    JOIN BronzeDB.dbo.br_products src
        ON src.SourceSystem    = tgt.SourceSystem
        AND src.SourceProductID = tgt.SourceProductID
        AND src.Brz_BatchID    = @BrzBatchID
        AND tgt.IsCurrent = 1
    WHERE
        ISNULL(tgt.ProductName,'')  <> ISNULL(src.ProductName,'')
     OR ISNULL(tgt.BasePrice,0)     <> ISNULL(src.BasePrice,0)
     OR ISNULL(tgt.CostPrice,0)     <> ISNULL(src.CostPrice,0)
     OR ISNULL(tgt.StockQty,0)      <> ISNULL(src.StockQty,0)
     OR ISNULL(tgt.IsActive,0)      <> ISNULL(src.IsActive,0);

    -- Step 2: Insert new current row (new + changed)
    INSERT INTO dbo.dim_product
        (SourceSystem, SourceProductID, SKU_Barcode, ProductName,
         CategoryKey, BasePrice, CostPrice, GrossMarginPct,
         StockQty, Weight_kg, IsActive, LaunchDate,
         IsCurrent, ValidFrom, ValidTo,
         Slv_LoadedAt, Slv_BatchID)
    SELECT
        brz.SourceSystem,
        brz.SourceProductID,
        brz.SKU_Barcode,
        brz.ProductName,
        dc.CategoryKey,
        brz.BasePrice,
        brz.CostPrice,
        -- GrossMarginPct
        CASE WHEN ISNULL(brz.BasePrice,0) > 0
             THEN CAST(((brz.BasePrice - ISNULL(brz.CostPrice,0)) / brz.BasePrice) * 100
                       AS DECIMAL(6,2))
             ELSE NULL END,
        brz.StockQty,
        brz.Weight_kg,
        brz.IsActive,
        brz.LaunchDate,
        1, GETDATE(), NULL,
        GETDATE(), @SlvBatchID
    FROM BronzeDB.dbo.br_products brz
    LEFT JOIN dbo.dim_category dc
        ON dc.SourceSystem = brz.SourceSystem
        AND dc.SourceCategoryID = brz.SourceCategoryID
    WHERE brz.Brz_BatchID = @BrzBatchID
      -- insert if no current row exists
      AND NOT EXISTS (
            SELECT 1 FROM dbo.dim_product dp
            WHERE dp.SourceSystem    = brz.SourceSystem
              AND dp.SourceProductID = brz.SourceProductID
              AND dp.IsCurrent = 1
          );
END;
GO

-- ============================================================
-- SP: usp_Slv_Load_DimCustomer  (SCD2)
-- ============================================================
CREATE OR ALTER PROCEDURE dbo.usp_Slv_Load_DimCustomer
    @BrzBatchID INT,
    @SlvBatchID INT
AS
BEGIN
    SET NOCOUNT ON;

    -- Expire changed rows
    UPDATE tgt
    SET tgt.IsCurrent = 0,
        tgt.ValidTo   = GETDATE()
    FROM dbo.dim_customer tgt
    JOIN BronzeDB.dbo.br_customers src
        ON src.SourceSystem     = tgt.SourceSystem
        AND src.SourceCustomerID = tgt.SourceCustomerID
        AND src.Brz_BatchID     = @BrzBatchID
        AND tgt.IsCurrent = 1
    WHERE
        ISNULL(tgt.Email,'')       <> ISNULL(src.Email,'')
     OR ISNULL(tgt.LoyaltyTier,'') <> ISNULL(src.LoyaltyTier,'')
     OR ISNULL(tgt.IsActive,0)     <> ISNULL(src.IsActive,0)
     OR ISNULL(tgt.Phone,'')       <> ISNULL(src.Phone,'');

    -- Insert new / changed records
    INSERT INTO dbo.dim_customer
        (SourceSystem, SourceCustomerID, FirstName, LastName, FullName,
         Email, Phone, DateOfBirth, AgeYears,
         Gender, LoyaltyTier, RegisteredDate, IsActive, CountryCode,
         IsCurrent, ValidFrom, ValidTo, Slv_LoadedAt, Slv_BatchID)
    SELECT
        brz.SourceSystem,
        brz.SourceCustomerID,
        brz.FirstName,
        brz.LastName,
        LTRIM(RTRIM(ISNULL(brz.FirstName,'') + ' ' + ISNULL(brz.LastName,''))) AS FullName,
        brz.Email,
        brz.Phone,
        brz.DateOfBirth,
        -- age in years at load time
        CASE WHEN brz.DateOfBirth IS NOT NULL AND brz.DateOfBirth <= CAST(GETDATE() AS DATE)
             THEN DATEDIFF(YEAR, brz.DateOfBirth, GETDATE())
                  - CASE WHEN MONTH(brz.DateOfBirth) * 100 + DAY(brz.DateOfBirth)
                              > MONTH(GETDATE()) * 100 + DAY(GETDATE())
                         THEN 1 ELSE 0 END
             ELSE NULL END,
        -- normalise gender: M->Male, F->Female, O->Other, else Unknown
        CASE brz.Gender
            WHEN 'M' THEN 'Male'
            WHEN 'F' THEN 'Female'
            WHEN 'O' THEN 'Other'
            ELSE 'Unknown' END,
        -- normalise loyalty tier
        CASE WHEN brz.LoyaltyTier IN ('Bronze','Silver','Gold','Platinum')
             THEN brz.LoyaltyTier ELSE 'Unknown' END,
        brz.RegisteredDate,
        brz.IsActive,
        brz.CountryCode,
        1, GETDATE(), NULL,
        GETDATE(), @SlvBatchID
    FROM BronzeDB.dbo.br_customers brz
    WHERE brz.Brz_BatchID = @BrzBatchID
      AND NOT EXISTS (
            SELECT 1 FROM dbo.dim_customer dc
            WHERE dc.SourceSystem     = brz.SourceSystem
              AND dc.SourceCustomerID = brz.SourceCustomerID
              AND dc.IsCurrent = 1
          );
END;
GO

-- ============================================================
-- SP: usp_Slv_Load_DimPromotion
-- ============================================================
CREATE OR ALTER PROCEDURE dbo.usp_Slv_Load_DimPromotion
    @BrzBatchID INT,
    @SlvBatchID INT
AS
BEGIN
    SET NOCOUNT ON;

    MERGE dbo.dim_promotion AS tgt
    USING (
        SELECT SourceSystem, SourcePromoID, PromoCode, Description,
               DiscountType, DiscountValue, MinOrderValue,
               StartDate, EndDate, IsActive, IsExpired
        FROM BronzeDB.dbo.br_promotions
        WHERE Brz_BatchID = @BrzBatchID
    ) src
    ON tgt.SourceSystem = src.SourceSystem AND tgt.SourcePromoID = src.SourcePromoID
    WHEN MATCHED THEN UPDATE SET
        tgt.DiscountValue = src.DiscountValue, tgt.IsActive = src.IsActive,
        tgt.IsExpired = src.IsExpired, tgt.Slv_LoadedAt = GETDATE(), tgt.Slv_BatchID = @SlvBatchID
    WHEN NOT MATCHED THEN INSERT
        (SourceSystem, SourcePromoID, PromoCode, Description, DiscountType,
         DiscountValue, MinOrderValue, StartDate, EndDate, IsActive, IsExpired,
         Slv_LoadedAt, Slv_BatchID)
    VALUES
        (src.SourceSystem, src.SourcePromoID, src.PromoCode, src.Description,
         src.DiscountType, src.DiscountValue, src.MinOrderValue, src.StartDate,
         src.EndDate, src.IsActive, src.IsExpired, GETDATE(), @SlvBatchID);
END;
GO

-- ============================================================
-- SP: usp_Slv_Load_DimLocation
-- ============================================================
CREATE OR ALTER PROCEDURE dbo.usp_Slv_Load_DimLocation
    @BrzBatchID INT,
    @SlvBatchID INT
AS
BEGIN
    SET NOCOUNT ON;

    INSERT INTO dbo.dim_location (City, State, PinCode, CountryCode, Slv_LoadedAt, Slv_BatchID)
    SELECT DISTINCT City, State, PinCode, 'IN', GETDATE(), @SlvBatchID
    FROM BronzeDB.dbo.br_orders
    WHERE Brz_BatchID = @BrzBatchID
      AND City IS NOT NULL AND State IS NOT NULL AND PinCode IS NOT NULL
      AND NOT EXISTS (
            SELECT 1 FROM dbo.dim_location dl
            WHERE dl.City = br_orders.City
              AND dl.State = br_orders.State
              AND ISNULL(dl.PinCode,'') = ISNULL(br_orders.PinCode,'')
          );
END;
GO

-- ============================================================
-- SP: usp_Slv_Load_DimWarehouse
-- ============================================================
CREATE OR ALTER PROCEDURE dbo.usp_Slv_Load_DimWarehouse
    @BrzBatchID INT,
    @SlvBatchID INT
AS
BEGIN
    SET NOCOUNT ON;

    MERGE dbo.dim_warehouse AS tgt
    USING (
        SELECT SourceWarehouseID, WarehouseName, City, State, CountryCode,
               CapacityUnits, IsOperational, ManagerName, OpenedOn
        FROM BronzeDB.dbo.br_warehouses
        WHERE Brz_BatchID = @BrzBatchID
    ) src ON tgt.SourceWarehouseID = src.SourceWarehouseID
    WHEN MATCHED THEN UPDATE SET
        tgt.WarehouseName=src.WarehouseName, tgt.IsOperational=src.IsOperational,
        tgt.Slv_LoadedAt=GETDATE(), tgt.Slv_BatchID=@SlvBatchID
    WHEN NOT MATCHED THEN INSERT
        (SourceWarehouseID, WarehouseName, City, State, CountryCode,
         CapacityUnits, IsOperational, ManagerName, OpenedOn,
         Slv_LoadedAt, Slv_BatchID)
    VALUES
        (src.SourceWarehouseID, src.WarehouseName, src.City, src.State,
         src.CountryCode, src.CapacityUnits, src.IsOperational, src.ManagerName,
         src.OpenedOn, GETDATE(), @SlvBatchID);
END;
GO

-- ============================================================
-- SP: usp_Slv_Load_DimSupplier
-- ============================================================
CREATE OR ALTER PROCEDURE dbo.usp_Slv_Load_DimSupplier
    @BrzBatchID INT,
    @SlvBatchID INT
AS
BEGIN
    SET NOCOUNT ON;

    MERGE dbo.dim_supplier AS tgt
    USING (
        SELECT SourceSupplierID, SupplierName, Email, Phone, CountryCode,
               LeadDays, PayTerms, Rating, IsActive, OnboardDate
        FROM BronzeDB.dbo.br_suppliers
        WHERE Brz_BatchID = @BrzBatchID
    ) src ON tgt.SourceSupplierID = src.SourceSupplierID
    WHEN MATCHED THEN UPDATE SET
        tgt.Rating=src.Rating, tgt.IsActive=src.IsActive,
        tgt.Slv_LoadedAt=GETDATE(), tgt.Slv_BatchID=@SlvBatchID
    WHEN NOT MATCHED THEN INSERT
        (SourceSupplierID, SupplierName, Email, Phone, CountryCode,
         LeadDays, PayTerms, Rating, IsActive, OnboardDate,
         Slv_LoadedAt, Slv_BatchID)
    VALUES
        (src.SourceSupplierID, src.SupplierName, src.Email, src.Phone,
         src.CountryCode, src.LeadDays, src.PayTerms, src.Rating, src.IsActive,
         src.OnboardDate, GETDATE(), @SlvBatchID);
END;
GO

-- ============================================================
-- SP: usp_Slv_Load_FactSales
-- ============================================================
CREATE OR ALTER PROCEDURE dbo.usp_Slv_Load_FactSales
    @BrzBatchID INT,
    @SlvBatchID INT
AS
BEGIN
    SET NOCOUNT ON;

    INSERT INTO dbo.fact_sales
        (OrderDateKey, CustomerKey, ProductKey, CategoryKey, LocationKey,
         PromoKey, PaymentMethodKey,
         SourceSystem, SourceOrderID, SourceLineItemID, OrderStatus,
         Quantity, UnitPrice, LineTotal, Discount,
         GrossAmount, TaxAmount, ShippingAmount, NetPayable, AmountPaid,
         LineDiscrepancy, IsFulfilled,
         Slv_LoadedAt, Slv_BatchID)
    SELECT
        -- DateKey
        CAST(FORMAT(o.OrderDate,'yyyyMMdd') AS INT)          AS OrderDateKey,
        -- CustomerKey: lookup current SCD2 row
        dc.CustomerKey,
        -- ProductKey
        dp.ProductKey,
        -- CategoryKey from product
        dp.CategoryKey,
        -- LocationKey
        dl.LocationKey,
        -- PromoKey (nullable)
        prm.PromoKey,
        -- PaymentMethodKey
        ISNULL(pm.PaymentMethodKey,
               (SELECT PaymentMethodKey FROM dbo.dim_payment_method WHERE PaymentMethod='Unknown')) AS PaymentMethodKey,
        -- degenerate
        li.SourceSystem,
        o.SourceOrderID,
        li.SourceLineItemID,
        o.OrderStatus,
        -- measures
        li.Quantity,
        li.UnitPrice,
        li.LineTotal,
        li.Discount,
        o.GrossAmount,
        o.TaxAmount,
        o.ShippingAmount,
        o.NetPayable,
        pay.AmountPaid,
        li.LineDiscrepancy,
        o.IsFulfilled,
        GETDATE(), @SlvBatchID
    FROM BronzeDB.dbo.br_order_items li
    -- join to order header (same source system + order id)
    JOIN BronzeDB.dbo.br_orders o
        ON o.SourceSystem  = li.SourceSystem
        AND o.SourceOrderID = li.SourceOrderID
    -- resolve CustomerKey
    LEFT JOIN dbo.dim_customer dc
        ON dc.SourceSystem     = o.SourceSystem
        AND dc.SourceCustomerID = o.SourceCustomerID
        AND dc.IsCurrent = 1
    -- resolve ProductKey
    LEFT JOIN dbo.dim_product dp
        ON dp.SourceSystem    = li.SourceSystem
        AND dp.SourceProductID = li.SourceProductID
        AND dp.IsCurrent = 1
    -- resolve LocationKey
    LEFT JOIN dbo.dim_location dl
        ON dl.City    = o.City
        AND dl.State   = o.State
        AND ISNULL(dl.PinCode,'') = ISNULL(o.PinCode,'')
    -- resolve PromoKey (nullable)
    LEFT JOIN dbo.dim_promotion prm
        ON prm.SourceSystem  = o.SourceSystem
        AND prm.SourcePromoID = o.SourcePromoID
    -- resolve PaymentMethodKey (one payment per order, take latest Success)
    LEFT JOIN (
        SELECT SourceSystem, SourceOrderID, PaymentMethod,
               SUM(AmountPaid) AS AmountPaid
        FROM BronzeDB.dbo.br_payments
        WHERE Brz_BatchID = @BrzBatchID
        GROUP BY SourceSystem, SourceOrderID, PaymentMethod
    ) pay
        ON pay.SourceSystem  = o.SourceSystem
        AND pay.SourceOrderID = o.SourceOrderID
    LEFT JOIN dbo.dim_payment_method pm
        ON pm.PaymentMethod = pay.PaymentMethod
    WHERE li.Brz_BatchID = @BrzBatchID;
END;
GO

-- ============================================================
-- SP: usp_Slv_Load_FactReturns
-- ============================================================
CREATE OR ALTER PROCEDURE dbo.usp_Slv_Load_FactReturns
    @BrzBatchID INT,
    @SlvBatchID INT
AS
BEGIN
    SET NOCOUNT ON;

    INSERT INTO dbo.fact_returns
        (ReturnDateKey, CustomerKey, ProductKey, WarehouseKey,
         SourceSystem, SourceReturnID, SourceOrderID, SourceShipmentID,
         ReturnQty, RefundAmount, ReturnReason, ReturnStatus, IsRefunded,
         Slv_LoadedAt, Slv_BatchID)
    SELECT
        CAST(FORMAT(r.ReturnDate,'yyyyMMdd') AS INT)    AS ReturnDateKey,
        dc.CustomerKey,
        dp.ProductKey,
        dw.WarehouseKey,
        r.SourceSystem,
        r.SourceReturnID,
        r.SourceOrderID,
        r.SourceShipmentID,
        r.ReturnQty,
        r.RefundAmount,
        r.Reason,
        r.ReturnStatus,
        r.IsRefunded,
        GETDATE(), @SlvBatchID
    FROM BronzeDB.dbo.br_returns r
    -- customer via order
    LEFT JOIN BronzeDB.dbo.br_orders o
        ON o.SourceSystem  = r.SourceSystem
        AND o.SourceOrderID = r.SourceOrderID
    LEFT JOIN dbo.dim_customer dc
        ON dc.SourceSystem     = o.SourceSystem
        AND dc.SourceCustomerID = o.SourceCustomerID
        AND dc.IsCurrent = 1
    -- product via BarCode -> dim_product.SKU_Barcode
    LEFT JOIN dbo.dim_product dp
        ON dp.SKU_Barcode = r.ReturnSKU
        AND dp.IsCurrent  = 1
    -- warehouse via shipment
    LEFT JOIN BronzeDB.dbo.br_shipments s
        ON s.SourceShipmentID = r.SourceShipmentID
    LEFT JOIN dbo.dim_warehouse dw
        ON dw.SourceWarehouseID = s.SourceWarehouseID
    WHERE r.Brz_BatchID = @BrzBatchID;
END;
GO

-- ============================================================
-- SP: usp_Slv_Load_FactInventorySnapshot
-- ============================================================
CREATE OR ALTER PROCEDURE dbo.usp_Slv_Load_FactInventorySnapshot
    @BrzBatchID INT,
    @SlvBatchID INT
AS
BEGIN
    SET NOCOUNT ON;

    DECLARE @SnapshotDate INT = CAST(FORMAT(GETDATE(),'yyyyMMdd') AS INT);

    INSERT INTO dbo.fact_inventory_snapshot
        (SnapshotDateKey, ProductKey, WarehouseKey, SupplierKey,
         SourceSystem, BarCode,
         QtyOnHand, QtyReserved, QtyAvailable, ReorderLevel, ReplenishQty,
         IsLowStock, Slv_LoadedAt, Slv_BatchID)
    SELECT
        @SnapshotDate,
        dp.ProductKey,
        dw.WarehouseKey,
        ds.SupplierKey,
        'LogiShip',
        inv.BarCode,
        inv.QtyOnHand,
        inv.QtyReserved,
        inv.QtyAvailable,
        inv.ReorderLevel,
        inv.ReplenishQty,
        CASE WHEN ISNULL(inv.QtyAvailable,0) <= ISNULL(inv.ReorderLevel,0)
             THEN 1 ELSE 0 END,
        GETDATE(), @SlvBatchID
    FROM BronzeDB.dbo.br_inventory inv
    LEFT JOIN dbo.dim_product dp
        ON dp.SKU_Barcode = inv.BarCode
        AND dp.IsCurrent  = 1
    LEFT JOIN dbo.dim_warehouse dw
        ON dw.SourceWarehouseID = inv.SourceWarehouseID
    LEFT JOIN dbo.dim_supplier ds
        ON ds.SourceSupplierID = inv.SourceSupplierID
    WHERE inv.Brz_BatchID = @BrzBatchID;
END;
GO

-- ============================================================
-- SP: usp_Slv_Load_FactShipments
-- ============================================================
CREATE OR ALTER PROCEDURE dbo.usp_Slv_Load_FactShipments
    @BrzBatchID INT,
    @SlvBatchID INT
AS
BEGIN
    SET NOCOUNT ON;

    INSERT INTO dbo.fact_shipments
        (ShipmentDateKey, DeliveryDateKey, CustomerKey, WarehouseKey,
         SourceSystem, SourceShipmentID, SourceOrderID,
         CarrierCode, TrackingNumber, ShipmentStatus,
         ShippingCost, ChargedWeightKg, DeliveryDays, IsLateDelivery,
         Slv_LoadedAt, Slv_BatchID)
    SELECT
        CASE WHEN s.ShipmentDate IS NOT NULL
             THEN CAST(FORMAT(s.ShipmentDate,'yyyyMMdd') AS INT) ELSE NULL END,
        CASE WHEN s.ActualDelivery IS NOT NULL
             THEN CAST(FORMAT(s.ActualDelivery,'yyyyMMdd') AS INT) ELSE NULL END,
        dc.CustomerKey,
        dw.WarehouseKey,
        s.SourceSystem,
        s.SourceShipmentID,
        s.SourceOrderID,
        s.CarrierCode,
        s.TrackingNumber,
        s.ShipmentStatus,
        s.ShippingCost,
        s.ChargedWeightKg,
        s.DeliveryDays,
        s.IsLateDelivery,
        GETDATE(), @SlvBatchID
    FROM BronzeDB.dbo.br_shipments s
    LEFT JOIN BronzeDB.dbo.br_orders o
        ON o.SourceSystem  = s.SourceSystem
        AND o.SourceOrderID = s.SourceOrderID
    LEFT JOIN dbo.dim_customer dc
        ON dc.SourceSystem     = o.SourceSystem
        AND dc.SourceCustomerID = o.SourceCustomerID
        AND dc.IsCurrent = 1
    LEFT JOIN dbo.dim_warehouse dw
        ON dw.SourceWarehouseID = s.SourceWarehouseID
    WHERE s.Brz_BatchID = @BrzBatchID;
END;
GO

-- ============================================================
-- SP: usp_Slv_Load_FactProcurement
-- ============================================================
CREATE OR ALTER PROCEDURE dbo.usp_Slv_Load_FactProcurement
    @BrzBatchID INT,
    @SlvBatchID INT
AS
BEGIN
    SET NOCOUNT ON;

    INSERT INTO dbo.fact_procurement
        (PODateKey, ArrivalDateKey, SupplierKey, WarehouseKey,
         SourceSystem, SourcePOID, POStatus, Currency,
         TotalValue, LeadTimeDays, IsDelayed,
         Slv_LoadedAt, Slv_BatchID)
    SELECT
        CAST(FORMAT(p.PODate,'yyyyMMdd') AS INT),
        CASE WHEN p.ActualArrival IS NOT NULL
             THEN CAST(FORMAT(p.ActualArrival,'yyyyMMdd') AS INT) ELSE NULL END,
        ds.SupplierKey,
        dw.WarehouseKey,
        p.SourceSystem,
        p.SourcePOID,
        p.POStatus,
        p.Currency,
        p.TotalValue,
        p.LeadTimeDays,
        p.IsDelayed,
        GETDATE(), @SlvBatchID
    FROM BronzeDB.dbo.br_procurement p
    LEFT JOIN dbo.dim_supplier ds ON ds.SourceSupplierID = p.SourceSupplierID
    LEFT JOIN dbo.dim_warehouse dw ON dw.SourceWarehouseID = p.SourceWarehouseID
    WHERE p.Brz_BatchID = @BrzBatchID;
END;
GO

-- ============================================================
-- SP: usp_Slv_Load_All  (master orchestrator)
-- ============================================================
CREATE OR ALTER PROCEDURE dbo.usp_Slv_Load_All
    @BrzBatchID INT
AS
BEGIN
    SET NOCOUNT ON;

    INSERT INTO dbo.SilverLoadLog (BronzeBatchID, Notes)
    VALUES (@BrzBatchID, 'Silver load started');
    DECLARE @SlvBatchID INT = SCOPE_IDENTITY();

    BEGIN TRY
        -- Seed date dim if not already populated
        IF NOT EXISTS (SELECT 1 FROM dbo.dim_date WHERE DateKey = 20180101)
            EXEC dbo.usp_Slv_Seed_DateDim;

        -- Dimensions first (no FK enforcement but logical order matters)
        EXEC dbo.usp_Slv_Load_DimCategory    @BrzBatchID, @SlvBatchID;
        EXEC dbo.usp_Slv_Load_DimProduct     @BrzBatchID, @SlvBatchID;
        EXEC dbo.usp_Slv_Load_DimCustomer    @BrzBatchID, @SlvBatchID;
        EXEC dbo.usp_Slv_Load_DimPromotion   @BrzBatchID, @SlvBatchID;
        EXEC dbo.usp_Slv_Load_DimLocation    @BrzBatchID, @SlvBatchID;
        EXEC dbo.usp_Slv_Load_DimWarehouse   @BrzBatchID, @SlvBatchID;
        EXEC dbo.usp_Slv_Load_DimSupplier    @BrzBatchID, @SlvBatchID;

        -- Facts after dimensions
        EXEC dbo.usp_Slv_Load_FactSales              @BrzBatchID, @SlvBatchID;
        EXEC dbo.usp_Slv_Load_FactReturns            @BrzBatchID, @SlvBatchID;
        EXEC dbo.usp_Slv_Load_FactInventorySnapshot  @BrzBatchID, @SlvBatchID;
        EXEC dbo.usp_Slv_Load_FactShipments          @BrzBatchID, @SlvBatchID;
        EXEC dbo.usp_Slv_Load_FactProcurement        @BrzBatchID, @SlvBatchID;

        UPDATE dbo.SilverLoadLog
        SET RunFinishedAt=GETDATE(), Status='Success', Notes='All Silver tables loaded.'
        WHERE BatchID=@SlvBatchID;

        PRINT CONCAT('Silver load complete. SlvBatchID=', @SlvBatchID);
    END TRY
    BEGIN CATCH
        UPDATE dbo.SilverLoadLog
        SET RunFinishedAt=GETDATE(), Status='Failed', Notes=ERROR_MESSAGE()
        WHERE BatchID=@SlvBatchID;
        THROW;
    END CATCH;
END;
GO

PRINT '06_SP_Bronze_To_Silver.sql installed successfully.';
GO
