"""
Microsoft Entra ID (Azure AD) authentication — OAuth2 Authorization Code + PKCE.

Flow:
  1. Frontend calls GET /api/auth/microsoft/url  → gets the authorization URL
  2. User is redirected to Microsoft login (pal.tech Entra ID)
  3. Microsoft redirects back to the app with ?code=xxx&state=yyy
  4. Frontend calls POST /api/auth/microsoft/token with {code, code_verifier}
  5. Backend exchanges code for tokens, decodes user info, returns {name, email}

Requires in .env:
  AZURE_TENANT_ID   — your pal.tech Azure AD tenant ID (GUID)
  AZURE_CLIENT_ID   — App Registration client ID
  AZURE_REDIRECT_URI — must match what's registered in Azure AD (e.g. http://localhost)
"""
import json
import logging
import secrets
import hashlib
import base64
from typing import Optional

import httpx
from fastapi import APIRouter, Depends, HTTPException
from pydantic import BaseModel, EmailStr
from sqlalchemy.orm import Session
from passlib.context import CryptContext

from app.core.config import settings
from app.core.metadata_db import get_db
from app.core.auth_deps import create_access_token

_pwd_ctx = CryptContext(schemes=["bcrypt"], deprecated="auto")

logger = logging.getLogger(__name__)
router = APIRouter(prefix="/api/auth", tags=["auth"])

_MS_BASE = "https://login.microsoftonline.com/{tenant}"
_SCOPES = "openid profile email User.Read"


def _authority() -> str:
    return _MS_BASE.format(tenant=settings.azure_tenant_id or "common")


class TokenExchangeRequest(BaseModel):
    code: str
    code_verifier: str
    redirect_uri: Optional[str] = None


class UserInfo(BaseModel):
    name: str
    email: str
    org_id: Optional[str] = None
    role: Optional[str] = None
    token: Optional[str] = None    # JWT Bearer token — present after login
    given_name: Optional[str] = None
    tenant: Optional[str] = None
    oid: Optional[str] = None


@router.get("/microsoft/url")
def get_microsoft_auth_url(state: str = ""):
    """
    Return the Microsoft authorization URL.
    The frontend generates the code_verifier + code_challenge (PKCE)
    and passes the challenge here. State is echoed back after redirect.
    """
    if not settings.azure_client_id or not settings.azure_tenant_id:
        raise HTTPException(501, "Microsoft SSO not configured. Set AZURE_TENANT_ID and AZURE_CLIENT_ID in .env")

    redirect_uri = settings.azure_redirect_uri or "http://localhost"
    # Build auth URL — PKCE challenge is generated by the frontend
    params = {
        "client_id": settings.azure_client_id,
        "response_type": "code",
        "redirect_uri": redirect_uri,
        "scope": _SCOPES,
        "response_mode": "query",
        "state": state or secrets.token_urlsafe(16),
        "prompt": "select_account",
        # domain_hint restricts to pal.tech tenant
        "domain_hint": settings.azure_domain_hint or "",
    }
    # Remove empty params
    params = {k: v for k, v in params.items() if v}
    from urllib.parse import urlencode
    url = f"{_authority()}/oauth2/v2.0/authorize?{urlencode(params)}"
    return {"url": url, "redirect_uri": redirect_uri}


@router.post("/microsoft/token", response_model=UserInfo)
async def exchange_microsoft_token(req: TokenExchangeRequest):
    """
    Exchange the authorization code (+ PKCE verifier) for tokens.
    Returns decoded user info — name, email, tenant.
    """
    if not settings.azure_client_id or not settings.azure_tenant_id:
        raise HTTPException(501, "Microsoft SSO not configured")

    redirect_uri = req.redirect_uri or settings.azure_redirect_uri or "http://localhost"
    token_url = f"{_authority()}/oauth2/v2.0/token"

    data = {
        "client_id": settings.azure_client_id,
        "grant_type": "authorization_code",
        "code": req.code,
        "redirect_uri": redirect_uri,
        "code_verifier": req.code_verifier,
        "scope": _SCOPES,
    }

    async with httpx.AsyncClient(timeout=15) as client:
        token_resp = await client.post(token_url, data=data)

    if token_resp.status_code != 200:
        detail = token_resp.text[:300]
        logger.error("Microsoft token exchange failed: %s", detail)
        raise HTTPException(401, f"Token exchange failed: {detail}")

    tokens = token_resp.json()
    id_token = tokens.get("id_token", "")

    # Decode JWT payload (no signature verification needed — we got it directly from Microsoft)
    user = _decode_id_token(id_token)
    logger.info("Microsoft SSO login: %s (%s)", user.get("name"), user.get("email"))
    return UserInfo(
        name=user.get("name", user.get("preferred_username", "User")),
        email=user.get("email") or user.get("preferred_username", ""),
        given_name=user.get("given_name"),
        tenant=user.get("tid"),
        oid=user.get("oid"),
    )


@router.get("/config")
def get_auth_config():
    """Return non-secret auth config needed by the frontend to build the PKCE request."""
    return {
        "ms_configured": bool(settings.azure_client_id and settings.azure_tenant_id),
        "ms_client_id": settings.azure_client_id or "",
        "ms_tenant_id": settings.azure_tenant_id or "",
        "ms_redirect_uri": settings.azure_redirect_uri or "http://localhost",
        "ms_domain_hint": settings.azure_domain_hint or "",
    }


def _decode_id_token(id_token: str) -> dict:
    """Decode the JWT payload without signature verification (trusted source)."""
    try:
        parts = id_token.split(".")
        if len(parts) < 2:
            return {}
        payload = parts[1]
        # Pad to multiple of 4
        payload += "=" * (-len(payload) % 4)
        decoded = base64.urlsafe_b64decode(payload)
        return json.loads(decoded)
    except Exception as e:
        logger.warning("ID token decode failed: %s", e)
        return {}


# ── Local PostgreSQL user authentication ──────────────────────────────────────

class RegisterRequest(BaseModel):
    email: str
    password: str
    name: str


class LoginRequest(BaseModel):
    email: str
    password: str


@router.post("/register", response_model=UserInfo, status_code=201)
def register_user(req: RegisterRequest, db: Session = Depends(get_db)):
    """
    Create a new local user account. Passwords are hashed with bcrypt and
    stored in the PostgreSQL metadata database (users table).
    org_id is derived from the email domain. First user in org = admin.
    """
    from sqlalchemy import text

    email = req.email.lower().strip()
    # Check for duplicate email
    existing = db.execute(
        text("SELECT id FROM users WHERE email = :email"),
        {"email": email},
    ).fetchone()
    if existing:
        raise HTTPException(409, "An account with this email already exists.")

    # Derive org_id from email domain (e.g. user@pal.tech → pal.tech)
    org_id = email.split("@")[1] if "@" in email else "default"

    # First user in org becomes admin; subsequent users get data_engineer role
    org_count = db.execute(
        text("SELECT COUNT(*) FROM users WHERE org_id = :org"),
        {"org": org_id},
    ).scalar() or 0
    role = "admin" if org_count == 0 else "data_engineer"

    password_hash = _pwd_ctx.hash(req.password)
    db.execute(
        text(
            "INSERT INTO users (email, name, password_hash, org_id, role) "
            "VALUES (:email, :name, :password_hash, :org_id, :role)"
        ),
        {
            "email": email,
            "name": req.name.strip(),
            "password_hash": password_hash,
            "org_id": org_id,
            "role": role,
        },
    )
    db.commit()
    logger.info("New user registered: %s (org=%s role=%s)", email, org_id, role)
    return UserInfo(name=req.name.strip(), email=email, org_id=org_id, role=role)


@router.post("/login", response_model=UserInfo)
def login_user(req: LoginRequest, db: Session = Depends(get_db)):
    """
    Authenticate with email + password. Returns user info + JWT Bearer token.
    """
    from sqlalchemy import text

    email = req.email.lower().strip()
    row = db.execute(
        text("SELECT name, email, password_hash, org_id, role FROM users WHERE email = :email"),
        {"email": email},
    ).fetchone()

    if not row or not _pwd_ctx.verify(req.password, row.password_hash):
        raise HTTPException(401, "Invalid email or password.")

    # Update last_login timestamp
    db.execute(
        text("UPDATE users SET last_login = NOW() WHERE email = :email"),
        {"email": email},
    )
    db.commit()

    org_id = getattr(row, "org_id", None) or "default"
    role   = getattr(row, "role",   None) or "viewer"
    token  = create_access_token(email=email, name=row.name, org_id=org_id, role=role)

    logger.info("User login: %s (org=%s role=%s)", email, org_id, role)
    return UserInfo(name=row.name, email=row.email, org_id=org_id, role=role, token=token)
